version: 1.2
workflows:
  - name: DepthOfCoverageWorkflow
    subclass: WDL
    primaryDescriptorPath: /steps/DepthOfCoverage.wdl
  - name: CopySampleFilesWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/orchestration/CopySampleFilesWorkflow.wdl
  - name: DownloadOutputsWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/orchestration/DownloadOutputsWorkflow.wdl
  - name: UnitTestWorkflowSingleParticipant
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowOne.wdl
  - name: UnitTestWorkflowSingleSample
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowOne.wdl
  - name: UnitTestWorkflowSingleAlternate
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowOne.wdl
  - name: UnitTestWorkflowMultiParticipant
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowMany.wdl
  - name: UnitTestWorkflowMultiSample
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowMany.wdl
  - name: UnitTestWorkflowMultiAlternate
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowMany.wdl
  - name: E2ETestWorkflowOne
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/E2ETestWorkflowOne.wdl