version: 1.2
workflows:
  - name: DepthOfCoverageWorkflow
    subclass: WDL
    primaryDescriptorPath: /steps/DepthOfCoverage.wdl
  - name: CopySampleFilesWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/orchestration/CopySampleFilesWorkflow.wdl