version: 1.2
workflows:
  - name: DepthOfCoverageWorkflow
    subclass: WDL
    primaryDescriptorPath: /steps/DepthOfCoverage.wdl
    readMePath: /steps/DepthOfCoverage.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - DepthOfCoverage_*
  - name: AlamutBatchWorkflow
    subclass: WDL
    primaryDescriptorPath: /steps/AlamutBatch.wdl
    readMePath: /steps/AlamutBatch.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - AlamutBatch_*
  - name: BgwgsWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/bgwgs/BgwgsWorkflow.wdl
    readMePath: /workflows/bgwgs/BgwgsWorkflow.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - BGWGS_*
  - name: CopySampleFilesWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/orchestration/CopySampleFilesWorkflow.wdl
    readMePath: /workflows/orchestration/CopySampleFilesWorkflow.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - ignore-all-tags
  - name: DownloadOutputsWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/orchestration/DownloadOutputsWorkflow.wdl
    readMePath: /workflows/orchestration/DownloadOutputsWorkflow.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - ignore-all-tags
  - name: DownloadOutputsSetWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/orchestration/DownloadOutputsSetWorkflow.wdl
    readMePath: /workflows/orchestration/DownloadOutputsSetWorkflow.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - ignore-all-tags
  - name: UnitTestWorkflowSingleParticipant
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowOne.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - ignore-all-tags
  - name: UnitTestWorkflowSingleSample
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowOne.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - ignore-all-tags
  - name: UnitTestWorkflowSingleAlternate
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowOne.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - ignore-all-tags
  - name: UnitTestWorkflowMultiParticipant
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowMany.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - ignore-all-tags
  - name: UnitTestWorkflowMultiSample
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowMany.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - ignore-all-tags
  - name: UnitTestWorkflowMultiAlternate
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowMany.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - ignore-all-tags
  - name: E2ETestWorkflowOne
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/E2ETestWorkflowOne.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - ignore-all-tags
  - name: E2ETestWorkflowSet
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/E2ETestWorkflowSet.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - ignore-all-tags
  - name: TestWorkflowFailure
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/TestWorkflowFailure.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - ignore-all-tags
  - name: GATKWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/pgxrisk/GATKWorkflow.wdl
    readMePath: /workflows/pgxrisk/GATKWorkflow.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - ignore-all-tags
  - name: PGxWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/pgxrisk/PGxWorkflow.wdl
    readMePath: /workflows/pgxrisk/PGxWorkflow.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - PGX_*
  - name: RiskAllelesWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/pgxrisk/RiskAllelesWorkflow.wdl
    readMePath: /workflows/pgxrisk/RiskAllelesWorkflow.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - RISK_*
  - name: BahrainPipelinesWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/bahrain_project/BahrainPipelinesWorkflow.wdl
    readMePath: /workflows/bahrain_project/BahrainPipelinesWorkflow.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - BahrainPipelines_*
  - name: BgwgsPanelWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/bgwgs/BgwgsPanelWorkflow.wdl
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - GenomePanels_*
  - name: BiobankRoRAlamutWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/biobank_ror/BiobankRoRAlamutWorkflow.wdl
    readMePath: /workflows/biobank_ror/BiobankRoRAlamutWorkflow.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - BiobankRoR_*
  - name: BiobankRoRSamplePrepWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/biobank_ror/BiobankRoRSamplePrepWorkflow.wdl
    readMePath: /workflows/biobank_ror/BiobankRoRSamplePrepWorkflow.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - BiobankRoR_*
  - name: BiobankRoRSampleLoadingWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/biobank_ror/BiobankRoRSampleLoadingWorkflow.wdl
    readMePath: /workflows/biobank_ror/BiobankRoRSampleLoadingWorkflow.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - BiobankRoR_*
  - name: BiobankRoRFASTParsingWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/biobank_ror/BiobankRoRFASTParsing.wdl
    readMePath: /workflows/biobank_ror/BiobankRoRFASTParsing.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - BiobankRoR_*
  - name: BiobankRoRMergeFASTExportsWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/biobank_ror/BiobankRoRMergeFASTExports.wdl
    readMePath: /workflows/biobank_ror/BiobankRoRFASTMergeFASTExports.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - BiobankRoR_*
  - name: LmmgapWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/lmmgap/lmmgap.wdl
    filters:
      branches:
        - master
        - /.*lmmgap.*/
      tags:
        - LMMGAP_*
  - name: BiobankShardingWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/biobank-scrub/BiobankShardingWorkflow.wdl
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - BiobankSharding_*
  - name: BiobankScrubWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/biobank-scrub/BiobankScrubWorkflow.wdl
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - BiobankScrub_*
  - name: insiMWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/mutagenesis/insiM.wdl
    readMePath: /workflows/mutagenesis/insiM.md
    filters:
      branches:
        - fix/insim*
        - feature/insim*
      tags:
        - insiM_*
  - name: BamsurgeonWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/mutagenesis/bamsurgeon.wdl
    readMePath: /workflows/mutagenesis/bamsurgeon.md
    filters:
      branches:
        - fix/bamsurgeon*
        - feature/bamsurgeon*
      tags:
        - Bamsurgeon_*
  - name: Glimpse2Imputation
    subclass: WDL
    primaryDescriptorPath: /workflows/lowpassimputation/Glimpse2Imputation.wdl
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - Glimpse2Imputation_*
  - name: Glimpse2SplitReference
    subclass: WDL
    primaryDescriptorPath: /workflows/lowpassimputation/Glimpse2SplitReference.wdl
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - Glimpse2SplitReference_*
  - name: CTBHaplotypeCallerGvcf
    subclass: WDL
    primaryDescriptorPath: /workflows/joint_calling/CTBHaplotypeCallerGvcf.wdl
    readMePath: /workflows/joint_calling/CTBHaplotypeCallerGvcf.md
    filters:
      branches:
        - /.*[a-zA-Z0-9].*/
      tags:
        - CTBHaplotypeCallerGvcf_*