version: 1.2
workflows:
  - name: DepthOfCoverageWorkflow
    subclass: WDL
    primaryDescriptorPath: /steps/DepthOfCoverage.wdl
    readMePath: /steps/DepthOfCoverage.md
  - name: AlamutBatchWorkflow
    subclass: WDL
    primaryDescriptorPath: /steps/AlamutBatch.wdl
    readMePath: /steps/AlamutBatch.md
  - name: BgwgsWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/bgwgs/BgwgsWorkflow.wdl
    readMePath: /workflows/bgwgs/BgwgsWorkflow.md
    filters:
      branches:
        - master
        - /.*bgwgs.*/
      tags:
        - BGWGS_*
  - name: CopySampleFilesWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/orchestration/CopySampleFilesWorkflow.wdl
    readMePath: /workflows/orchestration/CopySampleFilesWorkflow.md
  - name: DownloadOutputsWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/orchestration/DownloadOutputsWorkflow.wdl
    readMePath: /workflows/orchestration/DownloadOutputsWorkflow.md
  - name: DownloadOutputsSetWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/orchestration/DownloadOutputsSetWorkflow.wdl
    readMePath: /workflows/orchestration/DownloadOutputsSetWorkflow.md
  - name: UnitTestWorkflowSingleParticipant
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowOne.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
  - name: UnitTestWorkflowSingleSample
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowOne.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
  - name: UnitTestWorkflowSingleAlternate
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowOne.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
  - name: UnitTestWorkflowMultiParticipant
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowMany.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
  - name: UnitTestWorkflowMultiSample
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowMany.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
  - name: UnitTestWorkflowMultiAlternate
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/UnitTestWorkflowMany.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
  - name: E2ETestWorkflowOne
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/E2ETestWorkflowOne.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
  - name: E2ETestWorkflowSet
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/E2ETestWorkflowSet.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
  - name: TestWorkflowFailure
    subclass: WDL
    primaryDescriptorPath: /workflows/qatesting/TestWorkflowFailure.wdl
    readMePath: /workflows/qatesting/QATestingWorkflows.md
  - name: GATKWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/pgxrisk/GATKWorkflow.wdl
    readMePath: /workflows/pgxrisk/GATKWorkflow.md
  - name: PGxWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/pgxrisk/PGxWorkflow.wdl
    readMePath: /workflows/pgxrisk/PGxWorkflow.md
  - name: RiskAllelesWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/pgxrisk/RiskAllelesWorkflow.wdl
    readMePath: /workflows/pgxrisk/RiskAllelesWorkflow.md
  - name: BgwgsPanelWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/bgwgs/BgwgsPanelWorkflow.wdl