# Pipeline that mirrors this repository to github.com/mgbpm/biofx-workflows on every commit
name: "$(Build.BuildId) - Mirror biofx-workflows repository to GitHub" 

trigger:
  branches:
    include:
    - '*'

parameters:
  - name: GitHubCredsVarGroup
    displayName: Variable group containing the GitHubUser and GitHubPat
    type: string
    default: GITHUB_MIRROR_CREDENTIALS

pool:
  vmImage: ubuntu-latest

variables:
  - group: "${{ parameters.GitHubCredsVarGroup }}"

steps:
- checkout: self
  path: fullclone
  persistCredentials: true

- bash: |
    cd fullclone
    repourl="$(git config --get remote.origin.url)"
    cd ../
    mkdir bareclone
    cd bareclone
    git -c http.extraheader="AUTHORIZATION: bearer ${SYSTEM_ACCESS_TOKEN}" clone --bare "${repourl}"
    cd $(ls)
    git push --mirror https://${GITHUBUSER}:${GITHUBPAT}@github.com/mgbpm/biofx-workflows.git
  displayName: 'Checkout bare repository and push to github'
  workingDirectory: $(Pipeline.Workspace)
  env:
    GITHUBUSER: "$(GitHubUser)"
    GITHUBPAT: "$(GitHubPat)"
    SYSTEM_ACCESS_TOKEN: "$(System.AccessToken)"
